### ISSUE TITLE
Pure JS no dependency version?

### ISSUE THREAD

**Issue by ogewan** [staaky/spinners#6]
while jQuery is ubiquitous enough to be an expected dependency, it still drives up the mem usage. That coupled with 7kb min file seems like a lot to add for a spinner.

**Comment by staaky** [comment]
I've personally switched to pure CSS based spinners in my projects. [Support for IE8 ends Jan 12](http://blogs.msdn.com/b/ie/archive/2014/08/07/stay-up-to-date-with-internet-explorer.aspx), so browsers should be ready for it. You can probably even do without a fallback.

You are of course free to fork and take out the jQuery if you feel like you still need a javascript spinner.
